# configuation for robot odometry EKF 

frequency: 50

two_d_mode: true 

publish_tf: false 

odom_frame: odom 
base_link_frame : base_link 
world_frame : odom 
# map_frame = map

odom0 : /odom_noise
odom0_config: [false, false, false,
              false,  false , true,
              true,   true , false,
              false,  false, true,
              false,  false, false]

odom0_differential: false

imu0 : /imu 

imu0_config: [false, false, false,
              false,  false , true,
              false,   false , false,
              false,  false, true,
              true,  false, false]


imu0_differential: false


pose_noise_covariance: [0.05, 0, 0, 0]